python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact False --interact_type 0 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact False --interact_type 0 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact False --interact_type 0 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact False --interact_type 0 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact False --interact_type 0 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact True --interact_type 0 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact True --interact_type 0 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact True --interact_type 0 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact True --interact_type 0 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact True --interact_type 0 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact True --interact_type 1 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact True --interact_type 1 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact True --interact_type 1 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact True --interact_type 1 --exp_file exp_interact_layer_4_3> log.txt
python -m train --use_postag False --use_suffix False --use_character_lstm False --is_interact True --interact_type 1 --exp_file exp_interact_layer_4_3> log.txt
